import { Inter } from 'next/font/google';

import { AppSettingsDialog } from '@/components/dialogs/app-settings';
import { Toaster } from '@/components/ui/toaster';
import { cn } from '@/lib/utils';
import { ReactQueryProvider } from '@/providers/react-query';

import './globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans', display: 'swap' });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={cn(
          'relative flex min-h-screen flex-col items-center justify-center bg-slate-50 px-4 py-8 dark:bg-slate-900',
          inter.className,
        )}
      >
        <ReactQueryProvider>
          {children}

          <div className="mt-4 flex w-full max-w-lg items-center justify-between">
            <p className="text-sm text-slate-500">Copyright {new Date().getFullYear()}</p>

            <AppSettingsDialog />
          </div>
        </ReactQueryProvider>

        <Toaster />
      </body>
    </html>
  );
}
